version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appwave
      MYSQL_USER: appwave_user
      MYSQL_PASSWORD: appwave_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_password"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build:
      context: .
    image: appswave:latest
    container_name: appswave-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/appwave
      SPRING_DATASOURCE_USERNAME: appwave_user
      SPRING_DATASOURCE_PASSWORD: appwave_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
